# Constants for use in extracting USDA FoodData ingredient

# FIELD KEYS
ENERGY_AGF_KEY = "Energy (Atwater General Factors)"
MEASURE_VALUE_KEY = "value"
MEASURE_UNIT_KEY = "unit"
DESCRIPTION_KEY = "description"
FDC_ID_KEY = "fdcId"
CATEGORY_KEY = "category"
CARBS_KEY = "carbs"
CALORIES_KEY = "calories"
SODIUM_KEY = "sodium"
FAT_KEY = "fat"
FIBER_KEY = "fiber"
SUGARS_KEY = "sugars"
PROTEIN_KEY = "protein"
PORTION_VALUE_KEY = "portion-value"
PORTION_ABBR_KEY = "portion-abbr"
PORTION_GWEIGHT_KEY = "portion-gweight"
PORTIONS_KEY = "portions"

# USDA FOOD DATA CATEGORIES TO EXCLUDE IN FINAL DATA
EXCLUDED_CATEGORIES = [
    "Fast Foods",
    "Meals, Entrees, and Side Dishes",
    "Baby Foods",
    "Restaurant Foods",
]

# BRAND NAMES
BRAND_NAMES = [
    "archway",
    "andrea's",
    "continental mills",
    "krusteaz",
    "goya",
    "crunchmaster",
    "george weston",
    "glutino",
    "heinz",
    "weight watcher",
    "interstate brands",
    "keebler",
    "kraft",
    "martha white foods",
    "mary's gone crackers",
    "mckee baking",
    "mission foods",
    "nabisco",
    "la ricura",
    "pepperidge farm",
    "pillsbury",
    "rudi's",
    "sage valley",
    "schar",
    "udi's",
    "van's",
    "bud light",
    "budweiser",
    "abbot",
    "arizona",
    "coca-cola",
    "nestle",
    "cytosport",
    "dannon",
    "amp",
    "monster",
    "red bull",
    "rockstar",
    "vault",
    "fuze",
    "gerolsteiner",
    "lipton brisk",
    "minute maid",
    "motts",
    "nestea",
    "ocean spray",
    "ovaltine",
    "quaker",
    "pepsico",
    "powerade",
    "gatorade",
    "propel",
    "slimfast",
    "snapple",
    "v8",
    "calistoga",
    "crystal geyser",
    "evian",
    "pepsi",
    "perrier",
    "poland spring",
    "wendy's",
    "zevia",
    "alpen",
    "puffins",
    "familia",
    "general mills",
    "health valley",
    "malt-o-meal",
    "post",
    "mom's best",
    "nature's path",
    "ralston",
    "uncle sam",
    "sun country",
    "weetabix",
    "cream of rice",
    "cream of wheat",
    "wheatena",
    "tinkyada",
    "ancient harvest",
    "de boles",
    "uncle ben",
    "kamut",
    "lifeway",
    "reddi wip",
    "chobani",
    "bolthouse",
    "naked juice",
    "odwalla",
    "house foods",
    "mori-nu",
    "silk",
    "vitasoy",
    "chosen roaster",
    "planters",
    "hormel",
    "oscar mayer",
    "luna bar",
    "mars snackfood",
    "power bar",
    "slim-fast",
    "south beach",
    "balance",
    "clif bar",
    "farley candy",
    "fritolay",
    "kashi",
    "kellogg",
    "m&m mars",
    "nutri-grain",
    "hain celestial",
    "benecol",
    "smart balance",
    "smart beat",
    "campbell's",
    "frito's",
    "tostitos",
    "bull's-eye",
    "kc masterpiece",
    "open pit",
    "sweet baby ray's",
    "texas pete",
    "tuong ot",
    "buitoni",
    "classico",
    "mezzetta",
    "tabasco",
    "smart soup",
    "healthy choice",
    "swanson",
    "5th avenue",
    "almond joy",
    "health bites",
    "hershey's",
    "kit kat",
    "krackel",
    "mounds",
    "mr. goodbar",
    "reese's",
    "rolo",
    "special dark",
    "symphony",
    "toblerone",
    "tootsie roll",
    "twizzlers",
    "york",
    "klondike",
    "popsicle",
    "fudgsicle",
    "breyers",
    "schiff,tiger",
    "equal",
    "splenda",
    "smucker",
    "bimbo bakeries",
    "caramello",
    "zespri",
    "hain",
    "whatchamacallit",
    "creamsicle",
    "hersheys",
    "sprite",
    "muscle milk",
    "amber",
    "full throttle",
    "crunch bar",
]